LLP-model: DarkLeptonicScalar
OnlySaveLLPEvents: true
beaconlaunches: true
bias: 1000000.0
both_prod_decay_inside: true
config_LLP: /home/axel/i3/track-gap-ana/simulation/scripts/checks/LLP-behind-detector/new-PROPOSAL/config_LLP.json
config_SM: /home/axel/i3/track-gap-ana/simulation/configs/PROPOSAL/config_SM_local.json
deepcore: false
detectorname: IC86
dirname: new-PROPOSAL/
efficiency: 1.0
emax: 10000.0
emin: 1000.0
enablehistogram: true
entry_margin: 150.0
eps: 3.0e-05
exit_margin: 150.0
filtertrigger: true
gamma: 2.0
gcdfile: /home/axel/i3/GeoCalibDetectorStatus_2021.Run135903.T00S1.Pass2_V1b_Snow211115.i3.gz
generatedefficiency: 0.0
genie: false
gpu: null
gpulib: opencl
histogramfilename: /home/axel/i3/track-gap-ana/simulation/scripts/checks/LLP-behind-detector/new-PROPOSAL/histogram.pkl
holeiceparametrization: /home/axel/i3/icetray/icetray-dev/src/ice-models/resources/models/ANGSENS/angsens/as.h2-50cm
icemodel: spice_3.2
icemodellocation: /home/axel/i3/icetray/icetray-dev/build/ice-models/resources/models/ICEMODEL
icetop: false
keepemptyevents: false
keepmctree: true
length: 1600.0
length_dc: 500.0
lowmem: false
mass: 110.0
mcpeseriesname: I3MCPESeriesMap
mcprescale: 1
mctreename: I3MCTree
mctype: corsika_weighted
min_LLP_length: 10.0
model: Hoerandel5_atmod12_SIBYLL
natural_rate: false
nevents: 10
notinice: false
nproc: 1
offset: 700.0
only_one_LLP: true
outputfile: /home/axel/i3/track-gap-ana/simulation/scripts/checks/LLP-behind-detector/new-PROPOSAL/LLPSimulation.DarkLeptonicScalar.mass-110.0.eps-3e-05.bias-1000000.0.nevents-10.i3.gz
oversize: 1
parentdir: /home/axel/i3/track-gap-ana/simulation/scripts/checks/LLP-behind-detector/
photonseriesname: I3MCPESeriesMap
procnum: 0
propagatephotons: false
radius: 800.0
radius_dc: 150.0
rawphotonseriesname: null
runid: 0
runmphitfilter: true
sampleefficiency: 0.0
seed: 0
skipkeys: []
summaryfile: /home/axel/i3/track-gap-ana/simulation/scripts/checks/LLP-behind-detector/new-PROPOSAL/summary.json
tempdir: null
timeshiftskipkeys: []
trigger: true
use-clsim: false
usegpus: false
usegslrng: true
uselineartree: false
useonlydevicenumber: 0
volumecyl: false
x: 0.0
x_dc: 46.3
y: 0.0
y_dc: -34.9
z: 0.0
z_dc: -300.0
