LLP-model: DarkLeptonicScalar
mass: 110 # in MeV
eps: 3.0e-5
bias: 1.0e+6

model: Hoerandel5_atmod12_SIBYLL
gamma: 2.0
offset: 700.0
emin: 1000.0
emax: 10000.0
nevents: -1 # will be overwritten
gcdfile: /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/resources/GeoCalibDetectorStatus_2021.Run135903.T00S1.Pass2_V1b_Snow211115.i3.gz

propagatephotons: true
usegpus: true
usegslrng: true

only_one_LLP: true
OnlySaveLLPEvents: true
both_prod_decay_inside: true
min_LLP_length: 75.0
entry_margin: 150.0 # for good LLP check. min. depth in detector for prod?
exit_margin: 150.0 # for good LLP check. min. for decay

