model: Hoerandel5_atmod12_SIBYLL
gamma: 2.0
offset: 700.0
emin: 200.0
emax: 10000.0
nevents: 1
parentdir: /data/user/axelpo/test-sim-output/
dirname: test-may27/
gcdfile: /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/resources/GeoCalibDetectorStatus_2021.Run135903.T00S1.Pass2_V1b_Snow211115.i3.gz
config_SM: /data/user/axelpo/track-gap-ana/simulation/configs/PROPOSAL/config_SM.json
only_one_LLP: false
OnlySaveLLPEvents: false
both_prod_decay_inside: true
min_LLP_length: 100.0
entry_margin: 100.0 # for good LLP check. min. depth in detector for prod?
exit_margin: 100.0 # for good LLP check. min. for decay
LLP-model: DarkLeptonicScalar
propagatephotons: false
mass: 115
eps: 5.0e-05
bias: 3000000.0
