summaryfile: summary.json
enablehistogram: true
histogramfilename: histogram.pkl
nproc: 1
procnum: 0
seed: 0
usegslrng: false
icemodellocation: $I3_BUILD/ice-models/resources/models/ICEMODEL
icemodel: spice_3.2
holeiceparametrization: $I3_SRC/ice-models/resources/models/ANGSENS/angsens/as.h2-50cm
oversize: 1
efficiency: 1.0
propagatephotons: true
photonseriesname: I3MCPESeriesMap
gpu: null
usegpus: false
outputfile: ''
parentdir: ''
dirname: ''
model: Hoerandel5_atmod12_SIBYLL
gamma: 2.0
offset: 700.0
emin: 10000.0
emax: 10000000.0
length: 1600.0
radius: 800.0
x: 0.0
y: 0.0
z: 0.0
length_dc: 500.0
radius_dc: 150.0
x_dc: 46.3
y_dc: -34.9
z_dc: -300.0
deepcore: false
natural_rate: false
useonlydevicenumber: 0
rawphotonseriesname: null
keepmctree: true
nevents: 1
gcdfile: /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/resources/GeoCalibDetectorStatus_2021.Run135903.T00S1.Pass2_V1b_Snow211115.i3.gz
config_SM: /data/user/axelpo/track-gap-ana/simulation/configs/PROPOSAL/config_SM.json
config_LLP: null # best to leave it like this and use LLP model parameters instead
only_one_LLP: true
OnlySaveLLPEvents: true
both_prod_decay_inside: true
min_LLP_length: 100.0
entry_margin: 100.0 # for good LLP check. min. depth in detector for prod?
exit_margin: 100.0 # for good LLP check. min. for decay
LLP-model: DarkLeptonicScalar
mass: 115 # in MeV
eps: 5.0e-05
bias: 3000000.0
use-clsim: false
runmphitfilter: true
gpulib: opencl
volumecyl: false
mctreename: I3MCTree
keepemptyevents: false
tempdir: null
mctype: corsika_weighted
uselineartree: false
mcprescale: 1
icetop: false
notinice: false
genie: false
filtertrigger: true
trigger: true
lowmem: false
beaconlaunches: true
timeshiftskipkeys: []
sampleefficiency: 0.0
generatedefficiency: 0.0
runid: 0
mcpeseriesname: I3MCPESeriesMap
detectorname: IC86
skipkeys: []
